# Generated by Django 3.2.9 on 2022-04-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={'ordering': ('-id', '-created_at')},
        ),
    ]
