# Generated by Django 3.2.9 on 2022-04-05 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos_app', '0003_todos_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='parent_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='subtasks', to='todos_app.todos'),
        ),
    ]
