export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  CHECK_USER_SESSION_START: "user/CHECK_USER_SESSION_START",
  SIGN_IN_START: "user/SIGN_IN_START",
  SIGN_IN_SUCCESS: "user/SIGN_IN_SUCCESS",
  SIGN_IN_FAILED: "user/SIGN_IN_FAILED",

  SIGN_OUT_START: 'user/SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'user/SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILED: 'user/SIGN_OUT_FAILED',

  REFRESH_TOKEN_INIT: 'user/REFRESH_TOKEN_INIT',
  REFRESH_TOKEN_SUCCESS: 'user/REFRESH_TOKEN_SUCCESS',
  REFRESH_TOKEN_FAILED: 'user/REFRESH_TOKEN_FAILED',
};
