export const TODOS_ACTION_TYPES = {
  FETCH_TODOS_START: "todos/FETCH_TODOS_START",
  FETCH_TODOS_SUCCESS: "todos/FETCH_TODOS_SUCCESS",
  FETCH_TODOS_FAILED: "todos/FETCH_TODOS_FAILED",

  FETCH_TODO_START: "todos/FETCH_TODO_START",
  FETCH_TODO_SUCCESS: "todos/FETCH_TODO_SUCCESS",
  FETCH_TODO_FAILED: "todos/FETCH_TODO_FAILED",
};
