export const TODOS_ACTION_TYPES = {
  FETCH_TODOS_START: "todos/FETCH_TODOS_START",
  FETCH_TODOS_SUCCESS: "todos/FETCH_TODOS_SUCCESS",
  FETCH_TODOS_FAILED: "todos/FETCH_TODOS_FAILED",
  SET_TODOS_ITEMS: "todos/SET_TODOS_ITEMS",
  SET_TODOS_COUNT: "todos/SET_TODOS_COUNT",
};
