export const TODOS_ACTION_TYPES = {
  FETCH_TODOS_START: "todos/FETCH_TODOS_START",
  FETCH_TODOS_SUCCESS: "todos/FETCH_TODOS_SUCCESS",
  FETCH_TODOS_FAILED: "todos/FETCH_TODOS_FAILED",

  FETCH_TODO_START: "todos/FETCH_TODO_START",
  FETCH_TODO_SUCCESS: "todos/FETCH_TODO_SUCCESS",
  FETCH_TODO_FAILED: "todos/FETCH_TODO_FAILED",

  EDIT_TODO_START: "todos/EDIT_TODO_START",
  EDIT_TODO_SUCCESS: "todos/EDIT_TODO_SUCCESS",
  EDIT_TODO_FAILED: "todos/EDIT_TODO_FAILED",

  ADD_TODO_START: "todos/ADD_TODO_START",
  ADD_TODO_SUCCESS: "todos/ADD_TODO_SUCCESS",
  ADD_TODO_FAILED: "todos/ADD_TODO_FAILED",

  DELETE_TODO: "todos/DELETE_TODO",

  COMPLETE_TODO_START: "todos/COMPLETE_TODO_START",
  COMPLETE_TODO_SUCCESS: "todos/COMPLETE_TODO_SUCCESS",
  COMPLETE_TODO_FAILED: "todos/COMPLETE_TODO_FAILED",
};
